runtime: nodejs16
service: ml-tool-front

instance_class: F2

handlers:
  - url: /
    static_files: dist/formulario-ext/index.html
    upload: dist/formulario-ext/index.html

  - url: /
    static_dir: dist/formulario-ext